---
description:         PACT unpack_data.m configuration file
version:             1.0
date:                2014-03-28

extra:
  save_raw:          true
  src_dir:           ~/Documents/Project_data/PACT_data/test
  dest_dir:          ~/Documents/Project_data/PACT_data/test/unpack
  dtype:             <u4 # unsigned integer 32-bit, little endian (Windows)

load:
  EXP_START:         4
  EXP_END:           4
  NUM_EXP:           -1

unpack:
  Show_Image:        0
  BoardName:         [Board2004, Board9054]
  NumBoards:         2
  DataBlockSize:     1300
  PackSize:          8192
  NumDaqChnsBoard:   32
  TotFirings:        8
  NumElements:       512
  NumSegments:       1
  BadChannels:       [21,22,23,24,85,86,87,88]

display:
  span:              2
  # Wiener deconvolution flag
  wi:                false
  # Photodiode calibration flag
  pc:                false
  # "Exact" recon. flag
  exact:             false
  # Denoise flag
  denoise:           false

recon:
  algorithm:         envelope # envelope or delay-and-sum
  # algorithm:         delay-and-sum # envelope or delay-and-sum
  V_M:               1.51 # Acoustic velocity in km/s
  ini_angle:         225  # initial angle in degree
  # x_size:            15   # recon. image size
  # y_size:            15
  x_size:            25   # recon. image size
  y_size:            25
  z_size:            3
  resolution_factor: 20   # dxy = 1.0 mm / r.f.
  center_x:          0    # center of image
  # center_y:          -10
  center_y:          0
  fs:                40   # sampling frequency in MHz
  R:                 25   # radius of the ring array (mm)
  Len_R:             19.8 # focal length (mm)
  z_per_step:        0.1 # z step size (mm)
  z_resolution:      20   # resolution factor of z axis
